settings:
  max_posts_per_user: 3
  min_images_per_athlete: 3
  
  download_folder: "./data/insta/instagram_downloads"
  database_folder: "./data/faces/database"
  validation_folder : "./data/faces/validation"
  npz_basename: "face_db.npz"

athletes:
  - "fitnessbyaims"
  - "ahmd_ashkanani"
  - "keone_prodigy"